server:
  port: 8763
spring:
  application:
    name: client-feign
  #reids配置
  redis:
    host: 47.100.57.24
    port: 6369
    password: 123456
    database: 0
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/